### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/ethercalc_ynh#8]
Hi

Your app have failed to install on our CI.

We can find this in the log
```
../node_modules/nan/nan.h:324:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’

```
Maybe it's relative to this
```
npm WARN engine nodemailer@3.1.8: wanted: {"node":">=6.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
```

So, this app will be set at notworking status in one week. Except if theses errors are corrected.

You can find the complete log here
https://ci-apps.yunohost.org/jenkins/job/ethercalc%20(Community)/5/consoleFull

**Comment by frju365** [comment]
I don't think the problem is the npm package. On the github page of Ethercalc I see : 
"Runtime: Node.js (4.x preferred, should work with 0.8+)"

So 0.10 is good, even if a nvm installation, as aleks did in Wekan, is perhaps needed.

**Comment by kemenaran** [comment]
It also seems that the `conf/app.src` is missing from the git repository (while being required by the install script). @Rafi594 do you know anything about this?

**Comment by decentral1se** [comment]
I've resolve this now by installing a compatible version of Node. See https://github.com/YunoHost-Apps/ethercalc_ynh/pull/15.
